version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: org_mgmt_postgres
    environment:
      POSTGRES_DB: master_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  app:
    build: .
    container_name: org_mgmt_app
    ports:
      - "8000:8000"
    environment:
      - MASTER_DB_URL=postgresql://postgres:password@postgres:5432/master_db
      - ORG_DB_HOST=postgres
      - ORG_DB_PORT=5432
      - ORG_DB_USER=postgres
      - ORG_DB_PASSWORD=password
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: 